# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 4d2a6374d2ecc657f2a60f618dac22840c239a7da7a7703c4976c4e4725dfc6bb4e8b8964fba453143b2f51cc25dc706f6ab51a129521ccd16bba8b293d4b0c6

test:
  secret_key_base: 0cab4ca0859d79e64bc88864e67b3c6dbd631423d57bb296eb63fcd57eada7614854c3830b542c01f181d1a8051e880fd8df742cae94d2d15e0dd624d3bcb431

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
